### PR TITLE
:bug: fix(Blog): enable `no-underline` for heading links

### PR DESCRIPTION
**Pull request by jsun969**
I met this problem in my code too. jsun969/jsundotlol@c336e24  
Hope this can help you!

Btw, I saw you've removed the issue so I sent a twitter message to you about it. Hope it didn't bother you ❤️

### CODE REVIEW

**Comment by Moshyfawn** [comment]
Ah, you right! I was having some issues with applying links to headings with the plugin for some reason.

I've settled on keeping all links underlined, but forgot to remove the `class` lol

It actually ties into my planed updated to the blog, so I'm happy to merge it.

Thank you, Justin! I appreciate you taking the time to create an actual PR for my blog! 🖤

**Comment by Moshyfawn** [comment]
> My editor seems to automatically change the import order. You can swap it back if you don't like it 😟

No worries!

**Review by Moshyfawn — APPROVED** [review]

**Comment by jsun969** [comment]
> 

np if you plan to have underline if you like it.
btw, my solution is add underline when hover it. This is my code:

https://github.com/jsun969/jsundotlol/blob/ed0649ecb72f30cf041745c1f38a3ca76d55cf10/src/pages/blog/%5Bslug%5D.astro#L33-35

**Comment by Moshyfawn** [comment]
> np if you plan to have underline if you like it. btw, my solution is add underline when hover it. This is my code:
> 
> https://github.com/jsun969/jsundotlol/blob/ed0649ecb72f30cf041745c1f38a3ca76d55cf10/src/pages/blog/%5Bslug%5D.astro#L33-L35
> 
> (I use underline color cuz I need transition. You can still use `no-underline`)

I'm thinking a "link" SVG show up on heading hover. That's the behaviour I was going for, but got into some weirdness with the plugin 🙂

**Comment by jsun969** [comment]
> > np if you plan to have underline if you like it. btw, my solution is add underline when hover it. This is my code:
> > https://github.com/jsun969/jsundotlol/blob/ed0649ecb72f30cf041745c1f38a3ca76d55cf10/src/pages/blog/%5Bslug%5D.astro#L33-L35
> > (I use underline color cuz I need transition. You can still use `no-underline`)
> 
> I'm thinking a "link" SVG show up on heading hover. That's the behaviour I was going for, but got into some weirdness with the plugin 🙂

I also want to add a symbol or icon before the heading. but I still don't know how to implement 😓

**Comment by Moshyfawn** [comment]
> > > np if you plan to have underline if you like it. btw, my solution is add underline when hover it. This is my code:
> > > https://github.com/jsun969/jsundotlol/blob/ed0649ecb72f30cf041745c1f38a3ca76d55cf10/src/pages/blog/%5Bslug%5D.astro#L33-L35
> > > (I use underline color cuz I need transition. You can still use `no-underline`)
> > 
> > 
> > I'm thinking a "link" SVG show up on heading hover. That's the behaviour I was going for, but got into some weirdness with the plugin 🙂
> 
> I also want to add a symbol or icon before the heading. but I still don't know how to implement 😓

I have a couple of ideas, but I'm yet to find time to try them out.

Hoping to get some days off from work next week to work on some RHF content and my blog, including the heading links 😉

**Pull request merged**
